### ISSUE TITLE
UX - Add ability to drag tracks back to traktor?

### ISSUE THREAD

**Issue by Marak** [andersfischernielsen/Traktor-Transition-Finder#19]
Do you think it would be possible to support the ability to drag tracks from TraktorAutoNextSong back into a Traktor deck?

Right now, TraktorAutoNextSong will give me a suggestion, but then I'll have to go back into Traktor and search for that song by title or artist...not so awesome.

This UX might conflict with the ability to click on a track in TraktorAutoNextSong and get new suggestions...so you might want to create an explicit "suggest" button in TraktorAutoNextSong next to each track as to next confuse the UX.

**Comment by andersfischernielsen** [comment]
This is a lot of work for a relatively small feature. 
Some sort of mapping between the tracks and files on disk would have to be implemented, and this mapping would then have to be kept in the view, so that a drag would trigger an OS-level drag of the file (which I don't think is possible with electron).
