### ISSUE TITLE
Separation of recommendation algorithm from User-Interface

### ISSUE THREAD

**Issue by Marak** [andersfischernielsen/Traktor-Transition-Finder#4]
Very nice work!

I've been toying with the same idea for many years.

How hard would it be to separate / decouple the recommendation algorithm for tracks from the User Interface to Traktor?

It would be very nice to be able to have a stand-alone node.js module which worked only through text API calls ( not bound to any GUI ). This module would then become a dependency of this project.

I ask, because I've done a non-trivial amount of work into developing a good recommendation algorithm. Would be nice to combine efforts, or at least put your recommendation algorithm in a place where it could be re-used in other applications. Either way, separating these concerns will probably improve the quality of your project.

**Comment by andersfischernielsen** [comment]
Well, the recommendations work by calculating the weight of the edge to all other nodes (songs) in the graph built from the Traktor collection. 
So the recommendations are found by finding the current song in the graph and then sorting the edges from that song by weight. Which means that technically the recommendation logic is already pretty decoupled from the user interface.

When developing the F# backend I had a command line interface in F# for testing for a while. It would be relatively easy to build something like that again. :+1:

**Comment by andersfischernielsen** [comment]
A node.js module would have to interact with the Suave server component of the F# code like the GUI currently does. But that would just require some HTTP requests to work. It's definitely possible. :)

**Comment by Marak** [comment]
I just saw that the recommendation engine is built in F#.

I've downloaded the App and will try to experiment over the next weekend to start playing around.

I see a bit of comments located here: https://github.com/andersfischernielsen/TraktorAutoNextSong/blob/master/Project/Traktor/Collection.fs

Would you consider making a plain english documentation which details exactly how the recommendation engine works? No code, as much as just english directives.

Having a document like this could help in further discussion of the algorithm and possible ways it could be tweaked / improved. I could take what I have created and try and contribute to the conversation.

Either way, thanks again for releasing this project. I'm glad to see other people working on this idea.

**Comment by andersfischernielsen** [comment]
Awesome. 

I'll try to get to it when I have time. :+1: 
Uni is trying to drown me with assignments at the moment, but I'll see what I can do when I have time. 

No worries! :)

**Comment by andersfischernielsen** [comment]
@Marak The project is structured as follows: 

## Graph building backend

The backend is written in F# and parses a given collection.nml (which is plain XML). The document is passed into a list of Songs (a custom datatype containing Title, BPM etc.).
A weighted graph is then built from these songs, where every song is connected with an Edge (from, to and weight) to every other song. The weights are then calculated from the difference in BPM and key (see: http://www.mixedinkey.com/Book/Use-Advanced-Harmonic-Mixing-Techniques for a list of key differences that sound nice). 
The list of Edges from a given song is then sorted, and the best Edges are preserved. The rest are removed. The finished graph is then built. 
A simple HTTP server is started in order to send results to the frontend. The server accepts GET and POST requests for setting the collection location, and receiving a song from the frontend. 

## GUI frontend

The GUI frontend is written in Javascript (ES5), and is run as an app using Node.js and Electron. 
The frontend receives a song, hashes the file name, and sends this hash to the backend using a HTTP request. The backend then serves a result as JSON, that is displayed in the GUI.

**Comment by andersfischernielsen** [comment]
I hope that helps. :)
